export const Errors: Record<string, string> = {
    "100": 'Contract check error',
    "101": 'Protocol paused',
    "102": 'Length mismatch',
    "103": 'Send ETH failed',

    "200": 'Caller is not ActivePool',
    "201": 'Caller is not BorrowerOperations',
    "202": 'Caller is not CollateralManager',
    "203": 'Caller is not Stability Pool',
    "204": 'Caller is not TroveManager',
    "205": 'Caller is not TroveManagerLiquidations',
    "206": 'Caller is not TroveManagerRedemptions',
    "207": 'Caller is neither TroveManagerLiquidations nor TroveManagerRedemptions',
    "208": 'Caller is neither BorrowerOperations nor TroveManager',
    "209": 'Caller is neither BorrowerOperations nor TroveManagerLiquidations nor TroveManagerRedemptions',
    "210": 'Caller is neither BorrowerOperations nor TroveManagerRedemptions',
    "211": 'Caller is neither BorrowerOperations nor TroveManager nor StabilityPool nor TMR nor TML',

    "1": 'Trove is active',
    "2": 'Debt increase requires non-zero debtChange',
    "3": "Amount repaid must not be larger than the Trove's debt",
    "4": 'Operation not permitted during Recovery Mode',
    "5": 'Length is zero',
    "6": 'ETH does not active or is paused',
    "7": 'Collateral does not active or is paused',
    "8": 'Collateral amount is 0',
    "9": 'ETH does not active',
    "10": 'Collateral does not support or active',
    "11": 'Overlap Colls',
    "12": 'Duplicate Colls',
    "13": 'Cannot withdraw and add Coll',
    "14": 'There must be either a collateral change or a debt change',
    "15": 'Trove does not exist or is closed',
    "16": 'Collateral withdrawal not permitted Recovery Mode',
    "17": "Cannot decrease your Trove's ICR in Recovery Mode",
    "18": 'An operation that would result in ICR < MCR is not permitted',
    "19": 'Operation must leave trove with ICR >= CCR',
    "20": 'An operation that would result in TCR < CCR is not permitted',
    "21": "Trove's net debt must be greater than minimum",
    "22": 'Caller doesnt have enough USDE to make repayment',
    "23": 'Max fee percentage must less than or equal to 100%',
    "24": 'Max fee percentage must be between 0.25% and 100%',
    "30": 'Collateral already exists',
    "31": 'Collateral not pause',
    "32": 'Need at least one collateral support',
    "33": 'Collateral not support',
    "34": 'Ratio must be less than 100%',

    "35": 'Collateral not active',

    "40": 'No collateral available to claim',

    "50": "",

    "60": "Size can't be zero",
    "61": 'List is full',
    "62": 'List already contains the node',
    "63": 'Id cannot be zero',
    "64": 'ICR must be positive',
    "65": 'List does not contain the id',

    "70": 'USDE Loss < 1',
    "71": 'P = 0',
    "72": 'Cannot withdraw while there are troves with ICR < MCR',
    "73": 'User must have a non-zero deposit',
    "74": 'User must have no deposit',
    "75": 'Amount must be non-zero',
    "76": "Caller must have an active trove to withdraw collateral Gain to",
    "77": 'Caller must have non-zero Collateral Gain',
    "78": 'Must not already be a registered front end',
    "79": 'Tag must be a registered front end, or the zero address',

    "80": 'Kickback rate must be in range [0,1]',
    "81": 'Invalid mint amount',
    "82": '',
    "83": '',
    "84":  'Only one trove in the system',
    "85":  'newBaseRate must be > 0',
    "86":  'Fee would eat up all returned collateral',
    "87":  'Trove does not exist or is closed',
    "88": 'Unable to redeem any amount',
    "89": "Requested redemption amount must be <= user's USDE token balance",

    "90": 'Amount must be greater than zero',
    "91": 'Cannot redeem when TCR < MCR',
    "92": 'Redemptions are not allowed during bootstrap phase',
};
